# Generated by Django 5.2.1 on 2025-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_imatge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
